### ISSUE TITLE
bug: `infrahubctl` returns generic HTTP404 error when loading a schema that references an attribute with an non-existing id

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub-sdk-python#113]
### Component

Python SDK, infrahubctl

### Infrahub SDK version

0.14.1

### Current Behavior

When you try to load a schema that references an attribute with an id that does not exist in Infrahub, you get a generic error message on the HTTP 404 status code returned by the API server.

### Expected Behavior

`infrahubctl` should report an error message pointing the user to the mistake he made in the schema he wanted to load. Is HTTP 404 Not found even the right status code to use in this case?

### Steps to Reproduce

- spin up an instance of infrahub
- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Node
    namespace: Testing
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: description
        kind: Text
        optional: true
```
- now load this modified schema (notice that we renamed the attribute description to renamed, but we reference an invalid id)
```yaml
---
version: "1.0"
nodes:
  - name: Node
    namespace: Testing
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: renamed
        id: 123456
        kind: Text
        optional: true
```
