### ISSUE TITLE
bug: pytest plugin does not support the usage of relative imports

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub-sdk-python#166]
### Component

Python SDK

### Infrahub SDK version

1.1.0

### Current Behavior

You are unable to use the pytest plugin for user provided resources that use a relative import.

```bash
tests/test_resources.yml::infrahub_check__check_tag__smoke-test FAILED                                                 [100%]

========================================================== FAILURES ==========================================================
______________________________________ resource: infrahub_check__check_tag__smoke-test _______________________________________
attempted relative import with no known parent package
================================================== short test summary info ===================================================
FAILED tests/test_resources.yml::infrahub_check__check_tag__smoke-test
===================================================== 1 failed in 0.03s ======================================================

```

### Expected Behavior

The pytest plugin works for user provided resources that use relative imports

### Steps to Reproduce

- spin up an instance of Infrahub
- create a local repository and initialize it as a repository
- create the file `check_tag.py` in the directory
```python
from infrahub_sdk.checks import InfrahubCheck
from .utils import something

class MyCheck(InfrahubCheck):
    query = "check_tag"

    async def validate(self, data: dict) -> None:
        a = something()
        return
```
- create the file `utils.py` in the directory
```python
def something() -> str:
    return "something"
```
- create the file `check_tag.gql` in the directory
```graphql
query check_tag($name: String!) {
  BuiltinTag(name__value: $name) {
    edges {
      node {
	id
      }
    }
  }
}
```
- create the file `.infrahub.yml` in the directory
```yaml
---
check_definitions:
  - name: check_tag
    class_name: MyCheck
    file_path: "check_tag.py"
    targets: tags
    parameters:
      name: "name__value"
```
- create a tests directory in the repository
- create a file `tests/test_resources.yml`
```yaml
---
version: "1.0"
infrahub_tests:
  - resource: Check
    resource_name: check_tag
    tests:
      - name: smoke-test
        expect: PASS
        spec:
          kind: check-smoke
```
- in the root of the respository execute the following command
```bash
pytest -v
```
