### ISSUE TITLE
bug: Using Python keywords as attribute/relationship name breaks the SDK

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub-sdk-python#254]
### Component

API Server / GraphQL, Python SDK

### Current Behavior

It's currently possible to use Python keywords as the name of attributes or relationships within an Infrahub Schema. This doesn't cause a problem within Infrahub but it does break the SDK.

The Python keywords in question can be found within the keywords module:

```python
import keyword

print(keyword.kwlist)

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

```

To highlight the issue it's not possible to create a class as below in Python:

```python
class MyClass:
    class: str
```

### Expected Behavior

It would be better if these keywords were forbidden in the schema, alternatively we'd have to make some major changes to the SDK.

### Steps to Reproduce

1. Load the following schema to Infrahub

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/develop/schema.schema.json
---
version: '1.0'

nodes:
  - name: Character
    namespace: Rpg
    label: "Character"
    icon: "mdi:application-cog-outline"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    inherit_from: ["LineageOwner", "LineageSource"]
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: class
        peer: RpgClass
        optional: false
        cardinality: one
        kind: Attribute
  - name: Class
    namespace: Rpg
    label: "Class"
    icon: "mdi:server"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
```

2. Create an RpgClass called Wizard and an RpgCharacter called Gandalf with the class Wizard
3. Try to load the object using the SDK:

```python
from infrahub_sdk import InfrahubClient

client = InfrahubClient()

gandalf = await client.get(
    kind="RpgCharacter",
    id="Gandalf",
    populate_store=True,
    prefetch_relationships=True
)
```

4. Note that it's possible to access the class using the _ alias:

```python
In [2]: print(gandalf._class.peer.name.value)
Wizard
```

5. Note the SyntaxError when accessing the class name using the correct attribute name:

```python
In [3]: print(gandalf.class.peer.name.value)
  Cell In[3], line 1
    print(gandalf.class.peer.name.value)
                  ^
SyntaxError: invalid syntax

```
