### ISSUE TITLE
bug: Transform timeouts cannot be configured in a declarative manor

### ISSUE THREAD

**Issue by minitriga** [opsmill/infrahub-sdk-python#436]
### Infrahub SDK version

1.12.2

### Current Behavior

Currently transformation definitions in the `.infrahub.yml` file do not allow you to define a `timeout` value where as the `CoreTransformation` node accepts a timeout value. Any changes to the timeout value have to be done manually via the UI or API and not within the config file.

```
---
jinja2_transforms:
  - name: device_config_transform             # Unique name for your transform
    description: "device config transform"    # (optional)
    query: "device_config_query"              # Name or ID of the GraphQLQuery
    template_path: "device_config.j2"         # Path to the main Jinja2 template
```

### Expected Behavior

```
I would like the ability to specify my timeout value in the configuration file for J2 files. I'm not sure if python would use the class value of timeout or not. 
---
jinja2_transforms:
  - name: device_config_transform             # Unique name for your transform
    description: "device config transform"    # (optional)
    query: "device_config_query"              # Name or ID of the GraphQLQuery
    template_path: "device_config.j2"         # Path to the main Jinja2 template
    timeout: 180
```

### Steps to Reproduce

Nothing to reproduce
